---
title: "B"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```


```{r load_data, message=FALSE}

# Find all country directories
dirs <- list.dirs("./partB_data_files/")

#Drop root directory
dirs <- dirs[-1] 

#Extract file names from every directory and save them in a named list of character vectors
files <- sapply(dirs,list.files,pattern="*.xlsx",USE.NAMES=T,simplify = F)

#Create empty list 
datalist = list()


#Loop through directories and files within every directory
for (countrydir in names(files)) {
  for (file in files[[countrydir]]) {
    
    #Read in xlsx file, suppressing "New names" messages
    suppressMessages(excel<-countrydir %>% paste0("/",file) %>% read_xlsx())
    #Record sheet dimensions to use as reference points
    rowcount <- dim(excel)[1]
    colcount <- dim(excel)[2]
    #Extract main table, removing empty row and column in the second row and column of the resulting table
    data<-excel[c(5,seq(7,rowcount-3)),c(1,seq(3,colcount))]
    #Use first row as header
    colnames(data) <- data[1,]
    #Drop header names from the dataframe
    data <- data[-1,] 
    #Rename first column to year
    colnames(data)[1] <- "year"
    #Convert to long format
    data <- data %>% pivot_longer(2:length(data[1,]),names_to = "product",values_to = "value") 
    #Add flow and country from the sheet
    data <- data %>% add_column(flow=excel[2,3] %>% unlist %>% unname, country=excel[4,3] %>% unlist %>% unname) 
    #Reorder columns to fit format requirements
    data <- data %>% select(country,year,flow,product,value)
    #Add resulting dataframe to the list
    datalist[[file]] <- data
  }
}

#Bind dataframes together
fulldata <- do.call(bind_rows, datalist)

#Change to numeric data type and simultaneously coerce ".." values to NA
fulldata$value <- fulldata$value %>% as.numeric

#Count total rows in the dataframe and display
(totalrecords <- fulldata %>% nrow())

#Group data by product and print number of records. 
productrecords <- fulldata %>% group_by(product) %>% summarise(records=n())
#In case of every product, there are 8830 records.
(productrecords %>% count(records))
```
