---
title: "D"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(RSQLite)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(plotly)
library(tidyverse)
library(lubridate)
```

```{r}

# Read in dataframe from part C
ratingsdata<-readRDS("C_output.rds")

paste(object.size(ratingsdata) / 1048576,"MB") %>% print
# As the dataframe is only about 218 MB, loading it into memory is easily possible on any modern computer 
# Keeping the object in memory and running dplyr code proved faster than SQL in practice.

# SQL code provided for illustration throughout the code.
# Conencting to database
# db <- dbConnect(SQLite(), 'ratings.db')

# getting unique business type and Id for filters
BusinessTypeId <- ratingsdata %>% select(BusinessType,BusinessTypeID) %>% distinct()
# BusinessTypeId <- dbGetQuery(db, 'SELECT DISTINCT BusinessType,BusinessTypeID FROM dim_BusinessType;')


ui <- dashboardPage(
  
        dashboardHeader(
          title = "Ratings dashboard"
        ),
        #Sidebar definition
        dashboardSidebar(
          sidebarMenu(
            menuItem("Ratings over time", tabName = "Tab1", icon = icon("history")),
            menuItem("Sub-scores by ratings", tabName = "Tab2", icon = icon("project-diagram")),
            menuItem("Top local authorities by rating", tabName = "Tab3", icon = icon("map-marked"))
          )
        ),
        dashboardBody(
          tabItems(
            
            # First tab
            tabItem(tabName = "Tab1",
              fluidRow(
                box(width=12,h2("Density of specific rating values over time based on business type"),
                    br(),"
                    Lower ratings (0-2) gaining more weight in the last few years.")
              ),
              fluidRow(
                box(title ="Rating Value slider", width=6,
                   sliderInput(inputId = 'RatingValues','Rating Values:',0,5,2)),
                box(title="Business Type select", width=6,
                   selectInput(
                         inputId = 'BusinessType',
                         label = 'Business Types:',
                         choices = BusinessTypeId$BusinessType,
                         selected="Restaurant/Cafe/Canteen"
                ))),
              fluidRow(
                box(width=12,
                   #Plot Output
                   plotlyOutput(
                    outputId = 'Play1'
                   )
            ))),
            
            # Second tab
            tabItem(tabName ="Tab2",
                    fluidRow(
                      box(width=12,h2("Sub-score (penalties) distributions given rating value"),
                          br(),
                          "Most penalties (highest sub-scores) awarded for lack of confidence in management.")
                    ),
                    fluidRow(
                      # Business type distribution plot
                      box(title ="Rating Value slider",width=12,
                             sliderInput(
                               inputId = 'RatingValues2',
                               'Rating Values:',
                               0,
                               5,
                               1,
                     ))),
                     fluidRow(
                        box(width=12,
                           #Plot Output
                           plotlyOutput(outputId = 'Play2',height = "500px",width="100%")
                        )
            )),
            
            # Third tab
            tabItem(tabName ="Tab3",
                    fluidRow(
                      box(width=12,h2("Local authorities with highest proportion of a rating value"),
                          br(),
                          "Waltham Forest has the highest proportion (4%) of establishments with a rating of 0,
                          nearly 4 times as many as the runner-up.")
                    ),
                    fluidRow(
                      box(width=12,title="Rating Value Slider",
                          sliderInput(
                           inputId = 'RatingValues3',
                           'Rating Values:',
                           0,
                           5,
                           0
                     ))),
                     fluidRow(
                       box(width=12,
                        #Plot Output
                        plotlyOutput(
                           outputId = 'Play3',height = "500px",width="100%")  
                     ))
            )
          )
        )
)


server <- function(input, output, session) {
  
# 1. This plot is implementing Percentage of rating under Selected Category over the years

# Plotting a graph using ggplot showing year vs percentage of rating under each category  
    output$Play1 <- renderPlotly(
        {
          df <- ratingsdata %>% 
            filter(SchemeType=="FHRS"& BusinessType==input$BusinessType) %>% 
            select(RatingValue,RatingDate) %>% 
            mutate(year=lubridate::year(RatingDate)) %>% 
            count(year,RatingValue) %>% 
            left_join(ratingsdata %>% 
                        filter(SchemeType=="FHRS"& BusinessType==input$BusinessType) %>% 
                        mutate(year=lubridate::year(RatingDate))  %>% 
                        count(year) %>% rename(yearlycount=n), 
                      by="year") %>% 
            mutate(ratings_percentage=n/yearlycount) %>% filter(RatingValue==input$RatingValues)
            
          # df <- dbGetQuery(db,
          #      statement =
          #      'SELECT D.ratingValue,COUNT(D.ratingValue)/CAST(yearly_count AS REAL) AS ratings_percentage, Date.Year FROM fact_rating F
          #                INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #                INNER JOIN dim_BusinessType B ON B.BusinessTypeID=F.BusinessTypeID
          #                INNER JOIN dim_Date Date ON Date.RatingDate=F.RatingDate
          #                LEFT JOIN (
          #                    SELECT Date.Year, COUNT(D.ratingValue) AS yearly_count FROM fact_rating F
          #                    INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #                    INNER JOIN dim_BusinessType B ON B.BusinessTypeID=F.BusinessTypeID
          #                    INNER JOIN dim_Date Date ON Date.RatingDate=F.RatingDate
          #                    WHERE D.SchemeType = $Scheme
          #                    AND B.BusinessType = $Btype
          #                    GROUP BY Date.Year) DT ON DT.Year=Date.Year
          #                WHERE D.SchemeType = $Scheme
          #                AND B.BusinessType = $Btype
          #                AND D.ratingValue = $Rating
          #                GROUP BY D.ratingValue, Date.Year;'
          # ,list(Scheme="FHRS",Btype=input$BusinessType,Rating=input$RatingValues))
          
          plt1 <- plot_ly(df,x=~year,y=~ratings_percentage) %>% layout(title="Proportion of rating value by year and Business Type")
          plt1 %>% add_lines()
        }
    )

# 2. This navigation option describes the sub-score distributions of every rating value.    
   
   output$Play2 <- renderPlotly(
      {
          df <- ratingsdata %>% 
            filter(RatingValue==input$RatingValues2) %>% 
            count(Hygiene) %>% 
            add_column(Score="Hygiene") %>%  
            rename(level=Hygiene) %>% 
            bind_rows(ratingsdata %>% 
                        filter(RatingValue==input$RatingValues2) %>% 
                        count(Structural) %>% 
                        add_column(Score="Structural") %>%  
                        rename(level=Structural)
                      ) %>% 
            bind_rows(ratingsdata %>% 
                        filter(RatingValue==input$RatingValues2) %>% 
                        count(ConfidenceInManagement) %>% 
                        add_column(Score="ConfidenceInManagement") %>%  
                        rename(level=ConfidenceInManagement)
                      ) %>% 
            rename(Frequency=n) %>% 
            drop_na()
          
          # df<-dbGetQuery(db,
          #   statement="SELECT D.RatingValue, 'Hygiene' AS Score, F.Hygiene AS level, COUNT(F.Hygiene) AS Frequency
          #      FROM fact_rating F
          #      INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #      INNER JOIN dim_BusinessType B ON B.BusinessTypeID=F.BusinessTypeID
          #      WHERE D.RatingValue = $Rating
          #      AND F.Hygiene NOT NULL
          #      GROUP BY F.Hygiene
          #      UNION 
          #      SELECT D.RatingValue, 'Structural' AS Score, F.Structural AS level, COUNT(F.Structural) AS Frequency
          #      FROM fact_rating F
          #      INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #      INNER JOIN dim_BusinessType B ON B.BusinessTypeID=F.BusinessTypeID
          #      WHERE D.RatingValue = $Rating
          #      AND F.Structural NOT NULL
          #      GROUP BY F.Structural
          #      UNION 
          #      SELECT D.RatingValue, 'ConfidenceInManagement' AS Score, F.ConfidenceInManagement AS level, 
          #      COUNT(F.ConfidenceInManagement) AS Frequency 
          #      FROM fact_rating F
          #      INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #      INNER JOIN dim_BusinessType B ON B.BusinessTypeID=F.BusinessTypeID
          #      WHERE D.RatingValue = $Rating
          #      AND F.ConfidenceInManagement NOT NULL
          #      GROUP BY F.ConfidenceInManagement;",
          #  list(Rating=input$RatingValues2)) # Get rid of NA rows with 0 frequencies attached. (one row for each score)
          
          
          
          
          plt2<-plot_ly(df %>% filter(Score=="Hygiene"), x=~level,y=~Frequency) %>% add_bars(name="Hygiene")
          plt3<-plot_ly(df %>% filter(Score=="Structural"), x=~level,y=~Frequency) %>% add_bars(name="Structural")
          plt4<-plot_ly(df %>% filter(Score=="ConfidenceInManagement"), x=~level,y=~Frequency) %>% add_bars(name="Confidence In Management")
          subplot(plt2,plt3,plt4,nrows=1,shareY=T) %>% layout(title="Sub-score values (lower is better)")
      }
  )
    
#3. Top ten Authority for selected rating value

# This chart will render the  plot showing top 10 local Authorities based on rating at each level
    output$Play3 <- renderPlotly(
      {
          df<-ratingsdata %>% 
            filter(SchemeType=="FHRS") %>% 
            select(LocalAuthorityName,RatingValue) %>% 
            group_by(LocalAuthorityName) %>% 
            count(RatingValue) %>% 
            left_join(ratingsdata %>% 
                        filter(SchemeType=="FHRS") %>% 
                        group_by(LocalAuthorityName) %>% 
                        summarize(All_reviews=n()),by="LocalAuthorityName") %>% 
            mutate(Rating_percentage=n/All_reviews) %>% 
            filter(RatingValue==input$RatingValues3) %>% 
            arrange(desc(Rating_percentage)) %>% 
            head(10)
          
          # df <- dbGetQuery(db,
          #                  statement=" SELECT D.ratingValue, COUNT(D.ratingValue)/CAST(LocalAuthorityCount AS REAL) AS Rating_percentage,
          #                  L.LocalAuthorityName FROM fact_rating F
          #                  INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #                  INNER JOIN dim_LocalAuthority L on L.LocalAuthorityCode=F.LocalAuthorityCode 
          #                  LEFT JOIN (
          #                      SELECT L.LocalAuthorityName, COUNT(D.ratingValue) AS LocalAuthorityCount FROM fact_rating F
          #                      INNER JOIN dim_RatingTypes D ON F.RatingKey=D.RatingKey
          #                      INNER JOIN dim_LocalAuthority L on L.LocalAuthorityCode=F.LocalAuthorityCode 
          #                      WHERE D.SchemeType = $Scheme
          #                      GROUP BY L.LocalAuthorityName) DT ON DT.LocalAuthorityName=L.LocalAuthorityName
          #                  WHERE D.SchemeType = $Scheme
          #                  AND D.ratingValue = $Rating
          #                  GROUP BY L.LocalAuthorityName, D.RatingValue
          #                  ORDER BY Rating_percentage DESC
          #                  LIMIT 10;",
          #                  list(Scheme="FHRS",Rating=input$RatingValues3))
          
          plt4 <- plot_ly(df,x=~LocalAuthorityName,y=~Rating_percentage) %>% add_bars()
          plt4  %>% layout(xaxis = list(categoryorder = "total descending"),
                           title="Local Authorities with highest percentage of given rating value")
      }
    )
}

# Complete app with UI and server components
shinyApp(ui, server)
dbDisconnect(db)

```